hosts:
  myhost:
    config:
      db_database: WebLabTests
    runner: launch_minisample.py
    host: localhost
    processes:
      myprocess:
        config_file: process_config.py
        components:
          mycore:
            config_file: core_config.py
            type: core
          myexperiment:
            class: experiments.dummy.DummyExperiment
            config:
              dummy_verbose: false
            type: experiment
          mylab:
            config_file: lab_config.py
            type: laboratory

